name: Comment PR Ready to Merge

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches: ["main"]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            PR is ready to merge ! :+1:

      - name: Get PR Commits
        id: get_pr_commits
        uses: tim-actions/get-pr-commits@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Commits
        run: |
          echo "Commits:"
          echo "${{ steps.get_pr_commits.outputs }}"
