name: Comment PR Ready to Merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world PR is ready to merge ! :wave:
