name: Comment PR Ready to Merge

on:
  pull_request_review:
    types: [submitted]

jobs:
  comment_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            const comment = `This PR is ready to merge`;

            await github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });
