# name: Comment PR Ready to Merge

# on:
#   pull_request_review:
#     types: [submitted]
#   pull_request:
#     branches: ["main"]

# jobs:
#   comment_pr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           message: |
#             PR is ready to merge ! :+1:

#       - name: Print PR Head SHA
#         run: echo "${{ github.event.pull_request.head.sha }}" >> HEAD_SHA
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}

#       - name: Print PR Base SHA
#         run: echo "${{ github.event.pull_request.base.sha }}" >> BASE_SHA
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}

#       - name: Generate changelog
#         uses: requarks/changelog-action@v1
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           fromTag: ${{ env.BASE_SHA }}
#           toTag: ${{ env.HEAD_SHA }}
#           excludeTypes: "other"

#       - name: Commit CHANGELOG.md
#         uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           branch: ${{ github.head_ref }}
#           commit_message: "docs: update CHANGELOG.md (#${{ github.event.pull_request.number }}, branch: ${{ github.head_ref }})"
#           file_pattern: CHANGELOG.md
