name: Changelog CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch the last PR comment
        id: fetch_comment
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}" | tr -d '"')
          COMMENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/comments?issue=$PR_NUMBER&sort=created&order=desc" | jq -r '.[0].body' | grep -oP 'Release version:\s\K\d+\.\d+\.\d+')
          echo "::set-output name=comment::$COMMENT"

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          release_version: ${{ steps.fetch_comment.outputs.comment }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
