name: Changelog CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@main
      with:
        prefix: 'v' # optional, defaults to ''
    - name: Show the next version
      run: |
        echo ${{ steps.get_next_version.outputs.version }}
        echo ${{ steps.get_next_version.outputs.hasNextVersion }}
    
    - name: checkout v2  
    - uses: actions/checkout@v2
 
    - name: Run Changelog CI
      uses: saadmk11/changelog-ci@v1.1.2
      with:
          changelog_filename: CHANGELOG.md
          release_version: ${{ steps.get_next_version.outputs.hasNextVersion }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
