name: Changelog CI

on:
  pull_request_review:
    types: [submitted]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@main
        with:
          prefix: "v" # optional, defaults to ''

      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          release_version: ${{ steps.get_next_version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Changelog updated ! PR is ready to merge ! :+1:
