name: Generate Changelog

on:
  pull_request_review:
    types: [submitted]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Changelog
        id: generate-changelog
        uses: github-changelog-generator/github-changelog-generator@v1
        with:
          configure-sections:
            "added=\n\n### :memo: Documentation Changes\n^docs"
            "changed=\n\n### :construction_worker: Build System\n^ci"
          ignore-labels: "duplicate,question,invalid,wontfix"
          max-issues: 0
          exclude-pull-requests: false
          exclude-pull-request-labels: "skip-changelog"
          date-format: "yyyy-MM-dd"
          output: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update CHANGELOG.md"
          push: true
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Changelog updated. PR is ready to merge :+1:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}