name: Generate Changelog

on:
  pull_request_review:
    types: [submitted]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Changelog
        uses: saadmk11/changelog-ci@v1.0.4
        with:
          config-path: ".github/changelog-config.yml"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update CHANGELOG.md"
          push: true
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Changelog updated. PR is ready to merge :+1:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
