name: Changelog CI

on:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

      - name: Print Next Version
        run: echo "Next version = ${{steps.generate_release_tag.outputs.release_tag}}"

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          release_version: ${{ steps.generate_release_tag.outputs.release_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Changelog updated ! PR is ready to merge ! :+1:
