name: Generate Changelog

on:
  pull_request:
    branches: ["main"]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Changelog
        id: generate-changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Append Changelog to CHANGELOG.md
        run: |
          echo "${{ steps.generate-changelog.outputs.changelog }}" >> CHANGELOG.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update CHANGELOG.md"
          push: true
          branch: ${{ github.event.pull_request.head.ref }}

      - name: Comment PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            const comment = `This PR is ready to merge`;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comment
            });
