name: Changelog CI

on:
  pull_request_review:
    types: ["submitted"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

      - name: Print Next Version
        run: echo "Next version = ${{ steps.generate_release_tag.outputs.release_tag }}"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Conventional Changelog
        run: npm install -g conventional-changelog-cli

      - name: Generate Changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r ${{ steps.generate_release_tag.outputs.release_tag }}
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog to ${{ steps.generate_release_tag.outputs.release_tag }}"
          git push

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Changelog updated! PR is ready to merge! :+1:
