name: Github Release CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""

      - name: Generate random number and date
        id: generate_values
        run: |
          echo "RELEASE_NAME=Release $(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Print next version
        run: echo "Next version= ${{ steps.generate_release_tag.outputs.release_tag }}"

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_next_version.outputs.version }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
